# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('fields', models.TextField()),
                ('connections', models.ManyToManyField(related_name='_node_connections_+', to='backend_api.Node')),
            ],
        ),
    ]
