# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_auto_20180415_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='connections',
            field=models.ManyToManyField(to='backend_api.Node'),
        ),
    ]
