# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-25 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_auto_20180415_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.ManyToManyField(to='backend_api.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('attributes', models.ManyToManyField(to='backend_api.Attribute')),
            ],
        ),
        migrations.RemoveField(
            model_name='node',
            name='connections',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.AddField(
            model_name='relationship',
            name='fromSystem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relationsTo', to='backend_api.System'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='toSystem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relationsFrom', to='backend_api.System'),
        ),
    ]
