# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-25 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_auto_20180425_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='attributes',
            field=models.ManyToManyField(related_name='rel_attributes', to='backend_api.Attribute'),
        ),
    ]
