# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-25 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_auto_20180425_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='fromSystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationsTo', to='backend_api.System'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='toSystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationsFrom', to='backend_api.System'),
        ),
    ]
