# Generated by Django 2.0 on 2018-05-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_auto_20180425_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='color',
            field=models.TextField(default=''),
        ),
    ]
