# Generated by Django 2.0 on 2018-05-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_auto_20180505_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='color',
            field=models.TextField(default='#3c763d'),
        ),
    ]
